instblog-master/src/instblog/urls.py
from django.conf import settings 
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     url(r'^posts/', include("posts.urls" ,namespace='posts')),
     #url(r'^posts/$', "<appname>.views.<function name>"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instblog-master/src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from .views import *
	
	



urlpatterns = [
	 url(r'^$', post_list , name='list'),
 	 url(r'^create/$', post_create , name='post_create'), #2nd part here post_create is the name of the view
 	 url(r'^(?P<slug>[\w-]+)/edit/$', post_update ,name='update'),
 	 url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
 	 
 	 url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'), #this name can be used directly in a href in html files ealier we have to put whole url
 	 
 	 



 	 ]

instblog-master/src/posts/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse #to use get_absolute_url
from django.db.models.signals import pre_save # to implement slug (a dynamic name for posts not just the id)

from django.utils.text import slugify # to import slugify
# Create your models here.


def upload_location(instance, filename):
	return "%s/%s"%(instance.id , filename)


class Post(models.Model):
	
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1) #imp
	title = models.CharField(max_length=120)
	slug = models.SlugField(unique=True)
	image = models.ImageField(upload_to=upload_location,
	null = True,blank = True,
	height_field="height_field",
	width_field="width_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	content = models.TextField()
	
	updated = models.DateTimeField(auto_now = True, auto_now_add = False) #auto_now = True coz it needs to be updated
	timestamp = models.DateTimeField(auto_now =False, auto_now_add = True) #auto_now = False coz it doesnt need to be updated,its the time when post was created

	def __unicode__(self): #in python 3 __str __ is used
		return self.title

	def get_absolute_url(self): #it can be used in a href in html
		return reverse("posts:detail", kwargs={"slug":self.slug})

def create_slug(instance, new_slug=None): # slug implementation
	slug = slugify(instance.title)
		#"Tesla item 1" --> "tesla-item-1"

	if new_slug is not None:
		slug = new_slug
	qs = Post.objects.filter(slug=slug).order_by("-id")
	exists=qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug, qs.first().id)
		return create_slug(instance, new_slug =new_slug)
	return slug 


def pre_save_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)
		


 

pre_save.connect(pre_save_post_receiver, sender=Post)
		

instblog-master/src/posts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = [
		"title",
		"content",
		"image",
		
		]

class UserForm(forms.ModelForm): #blueprint of user form
	password = forms.CharField(widget=forms.PasswordInput) #password is not in admin user by default hence we have to declare it..widget=forms.PasswordInput = this to to make *** when inputting password
	class Meta: #information about class
		model = User # user model from admin
		fields = ['username','email','password']

instblog-master/src/posts/views.py
#Views handles the request and returns the response
# for shareable links
from django.contrib import messages #flash the successful msg
from django.http import HttpResponse, HttpResponseRedirect ,Http404 # HttpResponseRedirect:it redirects to the detail page after updating or creating a post
from django.shortcuts import render, get_object_or_404 , redirect 
from .models import Post
from .forms import *
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.shortcuts import render
from django.shortcuts import render,redirect #login page#redirect = to redirect user to any specified page after login
from django.contrib.auth import authenticate,login #login page#authenticate:to check the entered fields with existing ones in db
from django.views.generic import View#login page

from django.contrib.auth import logout
from django.contrib import messages


# Create your views here.

def post_create(request):
	if not request.user.is_staff or not request.user.is_superuser: #imp
		raise Http404


	form =PostForm(request.POST or None, request.FILES or None) # request.FILES or None:for images
	if form.is_valid():
		instance = form.save(commit = False)
		instance.user = request.user
		instance.save()
		#message success
		
		return HttpResponseRedirect(instance.get_absolute_url()) #redirects to detail page
	context={
		"form": form,
	}
	return render(request, "post_form.html", context) 

def post_detail(request,slug=None): #in url.py it is taking two arguments request and id hence here also we have to pass two
	instance = get_object_or_404(Post, slug =slug)
	
	context = {
			"instance":instance,
			"title": instance.title,    #inside context we declare variables which can be used in html files
			
	}



	return render(request,"post_detail.html",context)

def post_list(request):
	queryset_list = Post.objects.all().order_by("-timestamp") # order_by("-timestamp") : to order posts in increasing timestamp
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.all().order_by("-timestamp")
	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
			Q(title__icontains=query) |
			Q(content__icontains=query)
			).distinct()
	paginator = Paginator(queryset_list, 1000) # Show 25 contacts per page
	page_request_var ="page"
	page = request.GET.get("page_request_var")


	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
	# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
	# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)
	context = {
		"title":"Instblog",
		"object_list": queryset,
		"page_request_var" : page_request_var,
	}
	return render(request, "post_list.html",context)




    

    
def post_update(request,slug = None):
	#if not request.user.is_staff or not request.user.is_superuser:
		#raise Http404
	instance = get_object_or_404(Post, slug =slug)
	form =PostForm(request.POST or None,request.FILES or None,instance = instance )
	if form.is_valid():
		instance = form.save(commit = False)
		instance.save()
		# message success
		
		return HttpResponseRedirect(instance.get_absolute_url()) #redirects to detail page

	context = {
			"instance":instance,
			"title": instance.title,   
			 #inside context we declare variables which can be used in html files
			"form":form,
	}

	return render(request,"post_form.html",context)



def post_delete(request, slug=None):

	#if not request.user.is_staff or not request.user.is_superuser:
		#raise Http404
	instance = get_object_or_404(Post, slug=slug)
	instance.delete()
	messages.success(request, "Succesfully deleted")
	return redirect("posts:list", )


	

instblog-master/src/templates/base.html
{% load staticfiles %}
<html>

<head>
<title>{% block head_title %}Instblog{% endblock head_title %}</title> <!--changes the name in tab -->
<!-- Latest compiled and minified CSS -->
<style>
footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
</style>    
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> 



<style>
{% block style %}{% endblock style %}
</style>
</head>
<body>


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

</body>
<link rel = "stylesheet" href='{% static "css/base.css" %}' />





</div>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}INSTBlog{% endblock %}</title>
	<!--loads the path to your static files -->
	{% load staticfiles %}
	 <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
	
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!--<script src={% static 'music/js/main.js' %}"></script>--> 
</head>
<body>
	
	<nav class="navbar navbar-inverse">
	<div class="container-field"> <!--container-fluid-navigation bar fills the whole width of page -->
	
	<!--header -->

	<div class="navbar-header">  <!--navbar-header to indicate logo -->
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar"> <!--menu button-->
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span> <!--21 22 23 to make lines on menu button-->
		</button>
		<a class="navbar-brand" href="{% url 'posts:list' %}">INSTBlog</a>	
	</div>

	<!--navigation Items-->
	<div class="collapse navbar-collapse" id="topNavBar"> <!--items under this will collapse-->
	

		<ul class="nav navbar-nav">
			<li class=""> <!--active : the button currently active always lit up-->
				
		</ul>	

	<form class="navbar-form navbar-left" role="search" method="get" action="#">
			<div class="form-group"> <!--form-group:for styling-->
			<input type="text" class="form-control" name="q" value="{{request.GET.q}}">
			</div>
			<button type="submit" class="btn btn-default">
				Search
			</button>
		</form>

		

		<ul class="nav navbar-nav navbar-right">
			<li class="">
				<a href="{% url 'posts:post_create' %}">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Create New
				</a>
			</li>

		
		</ul>
	</div>
	
	</div>
</nav>
{% block body %} <!--to include this code in other html files-->
{% endblock %}
<div>

</div>


</div>
</body>
</html>

<!-- Latest compiled and minified JavaScript -->



{% block content %}

{% endblock content %}



</html>

instblog-master/src/templates/base_visitor.html
{% load staticfiles %}
<html>

<head>
<title>{% block head_title %}Instblog{% endblock head_title %}</title> <!--changes the name in tab -->
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> 



<style>
{% block style %}{% endblock style %}
</style>
</head>
<body>


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

</body>
<link rel = "stylesheet" href='{% static "css/base.css" %}' />

<div class='container'>




</div>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}INSTBlog{% endblock %}</title>
	<!--loads the path to your static files -->
	{% load staticfiles %}
	 <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!--<script src={% static 'music/js/main.js' %}"></script>--> 
</head>
<body>
	
	<nav class="navbar navbar-inverse">
	<div class="container-field"> <!--container-fluid-navigation bar fills the whole width of page -->
	
	<!--header -->

	<div class="navbar-header">  <!--navbar-header to indicate logo -->
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar"> <!--menu button-->
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span> <!--21 22 23 to make lines on menu button-->
		</button>
		<a class="navbar-brand" href="{% url 'posts:list' %}">INSTBlog</a>	
	</div>

	<!--navigation Items-->
	<div class="collapse navbar-collapse" id="topNavBar"> <!--items under this will collapse-->
		

	<ul class="nav navbar-nav">
			<li class=""> <!--active : the button currently active always lit up-->
				
			</li>
			<li class="">
				<a href="/posts/{{ instance.slug }}/edit/">  
					<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>&nbsp; Edit
					<!--glyphicon glyphicon-music : music icon before songs button ,&nbsp:for spacing between two buttons-->
				</a>
			</li> 

			<li class="">
				<a href="/posts/{{ instance.slug }}/delete/">
					<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>&nbsp; Delete
					<!--glyphicon glyphicon-music : music icon before songs button ,&nbsp:for spacing between two buttons-->
				</a>
			</li> 
		</ul> 

		

		<ul class="nav navbar-nav navbar-right">
			<li class="">
				<a href="{% url 'posts:post_create' %}">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Create New
				</a>
			</li>

		
		</ul>

		

		
	</div>
	
	</div>
</nav>
{% block body %} <!--to include this code in other html files-->
{% endblock %}
</body>
</html>

<!-- Latest compiled and minified JavaScript -->



{% block content %}

{% endblock content %}

</html>

instblog-master/src/templates/post_detail.html
{% extends "base_visitor.html" %}
{% block head_title %}{{instance.title}} | {{ block.super }}{% endblock head_title %} 



{% block content %}
<div class='col-sm-8 col-sm-offset-2'>
    <div class="thumbnail">
    	{% if instance.image %}
      	<img src ='{{ instance.image.url }}' class='img-responsive' />
      	{% endif %}

        <!--{{ request.build_absolute_uri }} link of my website -->
       <p> <div class="fb-like" data-href="request.build_absolute_uri" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></p>

       <p><div class="fb-send" data-href="request.build_absolute_uri"></div></p>

        <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
Facebook |
  </a>
     
      
</a>

      <a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>

      <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{instance.title}}&summary={{ share_string }} &source={{ request.build_absolute_uri }}">
Linkedin
</a>
      <div class="caption">
     
       <p><font   color="1e90ff" size="6">{{ title }}</font> &nbsp <font size="3" color="87ceeb">{{ instance.timestamp}}</font><small></p>
        <font size="3"><p>{{ instance.content | linebreaks }}</p></font>
       
        


      </div>
    </div>
  </div>
</div>




{% endblock content %}

instblog-master/src/templates/post_form.html
{% extends "base.html" %}

{% block content %} <!-- to include base.html we have to wrap this in those blocks also -->
<div class='col-sm-8 col-sm-offset-3'>
<h1>Form</h1> 

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}<!--action means to what url u want to send it to -->
{{ form.as_p}} <!--{{ form.as_p}} means form as paragraph -->
<input type='submit' class='btn btn-default' value='Create Post'>

</form>
</div>
{% endblock content %}

 

instblog-master/src/templates/post_list.html
{% extends "base.html" %} 
 
{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<!--<h1>{{ title }}</h1> <!-- {{ title }} to include context from views -->


{% for obj in object_list %}
<div class="row">
  <div class="col-sm-12 ">
    <div class="thumbnail">
        {% if obj.image %}
        <img src ='{{ obj.image.url }}' class='img-responsive' />
      	{% endif %}
        <div class="caption">
        	<h3><a href= '{{ obj.get_absolute_url }}'><p>{{ obj.title }}</a><small> &nbsp; {{ obj.timestamp | timesince  }} ago</p></small></h3>
          
        <p>{{ obj.content|linebreaks|truncatechars:120 }}</p>
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p> 
      </div>
    </div>
  </div>
</div>
{% endfor %}
<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{page_request_var}}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q}}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{page_request_var}}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q}}{% endif %}">next</a>
        {% endif %}
    </span>
</div>

</div>
<div>

</div>



{% endblock content %}